---
- name: Add Elastic apt-key for required packages
  apt_key:
    url: "{{elastic_apt_key}}"
    state: present

- name: Install apt-transport-https
  package:
    name: "apt-transport-https"
    state: present

- name: Add Elastic apt repository
  apt_repository:
    repo: "{{elastic_apt_repo}}"
    state: present

