---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include playbook variables
  include_vars: "all.yml"

- include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Install metricbeat
  package:
    name: metricbeat
    state: present

- name: Install auditbeat
  package:
    name: auditbeat
    state: present

- name: Install filebeat
  package:
    name: filebeat
    state: present

- name: Install packetbeat
  package:
    name: packetbeat
    state: present

- name: Configure metricbeat.yml
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: '0600'

- name: Configure auditbeat.yml
  template:
    src: auditbeat.yml.j2
    dest: /etc/auditbeat/auditbeat.yml
    owner: root
    group: root
    mode: '0600'

- name: Configure filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0600'

- name: Enable filebeat system module
  shell: "filebeat modules enable system"

- name: Configure packetbeat.yml
  template:
    src: packetbeat.yml.j2
    dest: /etc/packetbeat/packetbeat.yml
    owner: root
    group: root
    mode: '0600'

- name: systemd auditbeat
  systemd:
    name: auditbeat
    state: started
    enabled: yes
    daemon_reload: yes

- name: systemd metricbeat
  systemd:
    name: metricbeat
    state: started
    enabled: yes
    daemon_reload: yes

- name: systemd packetbeat
  systemd:
    name: packetbeat
    state: started
    enabled: yes
    daemon_reload: yes

- name: systemd filebeat
  systemd:
    name: filebeat
    state: started
    enabled: yes
    daemon_reload: yes
