---
- name: Add Elastic apt-key for required packages
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Install apt-transport-https
  apt:
    name:
      apt-transport-https      

- name: Add Elastic apt repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present

- name: Install required apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - metricbeat
      - auditbeat
      - filebeat
      - packetbeat

- name: Configure metricbeat.yml
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: '0600'

- name: Configure auditbeat.yml
  template:
    src: auditbeat.yml.j2
    dest: /etc/auditbeat/auditbeat.yml
    owner: root
    group: root
    mode: '0600'

- name: Configure filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0600'

- name: Enable filebeat system module
  shell: "filebeat modules enable system"

- name: Configure packetbeat.yml
  template:
    src: packetbeat.yml.j2
    dest: /etc/packetbeat/packetbeat.yml
    owner: root
    group: root
    mode: '0600'

- name: systemd auditbeat
  systemd:
    name: auditbeat
    state: started
    enabled: yes
    daemon_reload: yes

- name: systemd metricbeat
  systemd:
    name: metricbeat
    state: started
    enabled: yes
    daemon_reload: yes

- name: systemd packetbeat
  systemd:
    name: packetbeat
    state: started
    enabled: yes
    daemon_reload: yes

- name: systemd filebeat
  systemd:
    name: filebeat
    state: started
    enabled: yes
    daemon_reload: yes
